# Generated by Django 5.2.4 on 2025-07-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hazardous', models.BooleanField(default=False)),
                ('requires_special_handling', models.BooleanField(default=False)),
                ('density_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('20', '20 feet'), ('40', '40 feet'), ('40HC', '40 feet High Cube'), ('45', '45 feet')], max_length=10)),
                ('type', models.CharField(choices=[('DRY', 'Dry Container'), ('REEFER', 'Refrigerated Container'), ('OPEN_TOP', 'Open Top Container'), ('FLAT_RACK', 'Flat Rack Container'), ('TANK', 'Tank Container')], max_length=20)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internal_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('internal_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('internal_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['size', 'type'],
            },
        ),
    ]
